# Generated by Django 4.1 on 2022-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hr_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_poster', models.ImageField(upload_to='movie_poster/')),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_story', models.CharField(max_length=700)),
                ('movie_starring', models.CharField(max_length=300)),
                ('movie_date', models.DateField()),
                ('movie_collection', models.CharField(max_length=50)),
            ],
        ),
    ]
