# Generated by Django 4.1.6 on 2023-07-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_hr_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_movies',
            name='movie_source',
            field=models.FileField(default=False, upload_to='movie_source/'),
        ),
    ]
