# Generated by Django 4.1.6 on 2023-07-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_hr_movies_movie_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_movies',
            name='movie_source',
            field=models.FileField(default='not available', upload_to='movie_source/'),
        ),
    ]
